set RENDER_OPTIONS="-DFLAT_SPAN -DFLAT_NUKAGE1_COLOR=65 -DFLAT_SKY_COLOR=3 -DWAD_FILE=\"DOOMST2.WAD\" -DMAPWIDTH=480 -DNR_OF_COLORS=2"
set CFLAGS="-DBIG_ENDIAN=4321 -DBYTE_ORDER=LITTLE_ENDIAN"

qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c am_map.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c d_items.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c d_main.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c f_finale.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c f_lib.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c g_game.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c hu_stuff.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c i_audio.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c info.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c m_cheat.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c m_menu.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c m_random.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_doors.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_enemy.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_enemy2.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_floor.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_inter.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_lights.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_map.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_maputl.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_mobj.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_plats.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_pspr.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_setup.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_sight.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_spec.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_switch.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_telept.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_tick.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c p_user.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c r_data.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c r_draw.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c r_plane.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c r_sky.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c r_things.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c sounds.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c st_pal.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c st_stuff.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c s_sound.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c tables.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c v_video.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c wi_lib.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c wi_stuff.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c w_wad.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c z_bmallo.c
qdos-gcc %CFLAGS% %RENDER_OPTIONS% -c z_zone.c
